AWSTemplateFormatVersion: 2010-09-09
#######################################################################################
# Application Parameter
#######################################################################################
Parameters:
  NetworkStackName:
    Description: "Name of an active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack."
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: "MyFirstApp-Network"
  WebServerKeyPair:
    Description: "Key pair for ssh into web server"
    Type: String
    Default: "sneha-keypair"

# This CloudFormation template deploys application server.
Resources:
  WebServerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: app-server-launch-config
      AssociatePublicIpAddress: true
      ImageId: ami-062f7200baf2fa504
      InstanceType: t2.micro
      KeyName: !Ref WebServerKeyPair
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NetworkStackName}-WebServerSecurityGroup"
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash -ex
          yum update -y
          yum install -y httpd
          cd /var/www/html
          echo "<html>I love YAML CloudFormation!!</html>" > /var/www/html/app.html
          chmod 755 app.html
          service httpd start
          chkconfig httpd on
  WebServerAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: app-server-asg
      LaunchConfigurationName: !Ref WebServerLaunchConfiguration
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnets"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-WebServer"
          PropagateAtLaunch: "true"
#######################################################################################
# Output
#######################################################################################
Outputs:
  WebServerLaunchConfiguration:
    Description: "Web server launcg configuration"
    Value: !Ref WebServerLaunchConfiguration
  WebServerAutoscalingGroup:
    Description: "Web server auto scaling group"
    Value: !Ref WebServerAutoscalingGroup